# -*- coding: utf-8 -*-
"""classes2ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dmMvp_zBIxx-HkeFUw8QYWBR47d5BxNy
"""

class ClassePai:

  var1 = "classe pai"

class ClasseFilha(ClassePai):
  pass

objeto_pai = ClassePai()
objeto_filho = ClasseFilha()

print (objeto_pai.var1)
print (objeto_filho.var1)