# -*- coding: utf-8 -*-
"""dicionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F9s5IydRZ9_FqMtKBq8Kch-nS3koT0wW
"""

meu_dicionario = {"A":"AMEIXA", "B":"BOLA", "C":"CARRO"}

for letra, palavra in meu_dicionario.items():
    print(letra, "-", palavra)

print(meu_dicionario)