# -*- coding: utf-8 -*-
"""elif.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15ehfnXFhOBJjEnkqtK5AA4AccuR4cvmr
"""

x = 1
y = 2

if x == y:
    print("numeros iguais")
elif y > x:
    print("y maior que x")
elif x < y:
    print("x menor que y")  
else:
    print("numeros diferentes")
    
#será executada a primeira condição verdadeira que ele encontrar