# -*- coding: utf-8 -*-
"""else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q1VtjyyY1DX2dHfgs1HWZxYA4lPQTIOm
"""

# -*- coding: utf-8 -*-
x = 1
y = 10

if x > y:
    print("x é maior que y")
else:
    print("x não é maior que y")