# -*- coding: utf-8 -*-
"""enumerate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14-5INMoVBIYcaaiiBA1u3KZItAq7Xcek
"""

#função enumerate

lista = ["abacate", "bola", "cachorro"]

for i, nome in enumerate(lista):
  print(i, nome)