# -*- coding: utf-8 -*-
"""for_range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5bA9WqkvK06BNCFCrg2jpLziW4krBmG
"""

for i in range(10,20,2):
    print(i)