# -*- coding: utf-8 -*-
"""for_listasipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-KJNSzg41mFdKhU6NJEAtGSlC1JuE0S
"""

lista1 = [1,2,3,4,5]
lista2 = ["anderson","soares","brazil"]
lista3 = [1, "mexico", 9.99, True]

for i in lista1:
    print(i)