# -*- coding: utf-8 -*-
"""funcoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13uv22TKnTiYJ_knOn9fIvbiO4t_ymcAm
"""

def print_text():
  print("Isso é um texto!")

print_text() #chamando a função

def print_isto(x):
  print(x)

print_isto("Python")

