# -*- coding: utf-8 -*-
"""funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vakADGIE5N8zPLzL6_qAd0znoyQfAnFo
"""

def soma(x, y):
  return(x+y)

a = soma (2, 3)
print(a)