# -*- coding: utf-8 -*-
"""grafico-de-barras

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mp4doDvB_VBEEQH3KblepYOQbQ63nZU9
"""

# Visualização de dados

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5]
y = [2, 3, 7, 1, 0]
titulo = "Gráfico de barras"
eixox = "Eixo X"
eixoy = "Eixo Y"

plt.title(titulo)
plt.xlabel(eixox)
plt.ylabel(eixoy)

plt.bar(x, y)
plt.show()

