# -*- coding: utf-8 -*-
"""graficos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gPc4qYg00T8MG8C3RohWDwq88WvdWnN
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0,2, 100)

len(x)

max(x)

min(x)

x

y = 2*x

plt.plot(x,y,"*")
plt.xlabel("Eixo X")
plt.ylabel("Eixo Y")
plt.title("Gráfico")
plt.show()

y = x**2

plt.plot(x,y,".g")
plt.xlabel("Eixo X")
plt.ylabel("Eixo Y")
plt.title("Gráfico")
plt.show()