# -*- coding: utf-8 -*-
"""if.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yp8JrFJoAMNRcZkyw-5mE1Y4FwUuwtqn
"""

# -*- coding: utf-8 -*-
x = 1
y = 10

if x > y:
    print("x é maior que y")
if y > x:
    print("y é maior que x")