# -*- coding: utf-8 -*-
"""inputipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GW2eZowto3lZQ9X4mxI_-ZQPiACN-Kv2
"""

valor1 = int(input("Digite um valor: "))
valor2 = int(input("Digite outro valor: "))
soma = valor1 + valor2
print(valor1, "+", valor2, "=", soma)