# -*- coding: utf-8 -*-
"""laco-for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ejiq2K742wWHmT7m5YmZaMdOh-TWe4M

Estrutura de Dados: Laço For
"""

lista = [1,2,3,4,5,6]

for x in lista:
  print(x)

for i in lista:
  if i%2 == 0:
    print(i)

#encontre os números pares na lista

