# -*- coding: utf-8 -*-
"""lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L5TopozllzlpsQwkrIUnKGNavxxSfqKM
"""

#funções lambda

valor = [1, 2, 3, 4, 5]

valor_dobrado = map(lambda i: i*2, valor)

valor_dobrado = list(valor_dobrado)
print(valor_dobrado)