# -*- coding: utf-8 -*-
"""listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PyOOhjBySMGGGUrBuwybtOGgRbpLmw28
"""

minha_lista1 = ["abacaxi", "melancia", "abacate"]
minha_lista2 = [1,2,3,4,5]
minha_lista3 = [1, "sapo", True, 9.99]

tamanho = len(minha_lista1) #verificar tamanho da lista
print(tamanho)

print (minha_lista3[3]) #posição do item na lista

del minha_lista3[1:4] #remover itens

del minha_lista2[:] #remover todos os itens

if "1" in minha_lista3:   #verificando se um item existe
  print("1 está na lista")

minha_lista4 = []  #lista vazia

minha_lista4.append("peixe")#adicionar itens

print(minha_lista1)
print(minha_lista2)
print(minha_lista3)
print(minha_lista4)