# -*- coding: utf-8 -*-
"""lista1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VSxxiQzyKefvCaKkkHRoh3LQ2jRlum1L
"""

nucleotideos = ["A","T","C","G"]

nucleotideos = sorted(nucleotideos)
 
print (nucleotideos)