# -*- coding: utf-8 -*-
"""list-comprehension

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-hyfFEgRPbKS9NqEt7WGXRzO8vUqB1C
"""

x = [1,2,3,4,5]
y = []

for i in x:
  y.append(i**2)

print(x)
print(y)



x = [1,2,3,4,5]
y = [i**2 for i in x]

print(x)
print(y)

#usando list comprehension

x = [1,2,3,4,5]
y = [i**2 for i in x]
z = [i for i in x if i%2==1]

print(z)