# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12AO0ANIU-r2_2jzPvIW7JbpLMawjXnLe
"""

for i in range(10):
  print(i) 

# a partir do zero

for i in range(10):
    print(i+1)

# a partir do um

for i in range(0,22,2):
  print(i)

# de dois em dois números