# -*- coding: utf-8 -*-
"""matriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCKHDDSSlFLAvJ3YM47OvSIR8DsNZqc4
"""

import numpy as np

Matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])

Matriz

#isso é uma matriz