# -*- coding: utf-8 -*-
"""meu_primeiro_codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r7BUbk0YezXgzy4Q8bzoqB7uJjvJBW9Y
"""

print("Olá mundo!")
print ("Estou de volta.")

import matplotlib.pyplot as plt