# -*- coding: utf-8 -*-
"""mini_calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fdhdp8TUqK_fkRIXShoa6X14RiHSCsrW
"""

num1 = int(input("Digite um número: "))
operador = str(input("Digite um operador: "))
num2 = int(input("Digite um número: "))

#soma

if operador == "+":
  resultado = num1 + num2

#subtração
elif operador == "-":
  resultado = num1 - num2

#multiplicação
elif operador == "*":
  resultado = num1 * num2

#divisão
elif operador =="/":
  resultado = num1 / num2

print(resultado)