# -*- coding: utf-8 -*-
"""numeroaleatorio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jY9x42s7QBbVERk-5MFdrXTy9oMmbTsJ
"""

import random

numero = random.randint(0, 1000)
print(numero)