# -*- coding: utf-8 -*-
"""operadores.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1305d0nv62WxNbwjY5E0_hlI76L9FV4Wm
"""

x = 2
y = 3
z = 3

print(x == y and x == z and z == y)