# -*- coding: utf-8 -*-
"""ordenacao_de_listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eza8UfWEMLIueTefrqzEkwqUpSO8ygmb
"""

lista = [3,2,1]

lista = sorted(lista)

print(lista)