# -*- coding: utf-8 -*-
"""reduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTJpjayYMaPRCxDQELz4T0qcuQQeb3hB
"""

#função reduce
from functools import reduce

def soma(x, y):
  return x+y

lista = [1, 3, 5, 10, 20]

soma = reduce(soma, lista)
print(soma)