# -*- coding: utf-8 -*-
"""soma_simples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLCcZbgm-VO_N-XVqhVOE4oStbly0Qn4
"""

x = 2
y = 3
print (x+y)