# -*- coding: utf-8 -*-
"""strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c88foKNyztBgn33DU5YanIfCCC_OrZC6
"""

a = "Anderson"
b = "Soares"

concatenar = a + " " + b
print(concatenar)

#concatenação

seq = "Anderson Soares"
caracteres = len(seq)
print (caracteres)

#tamanho da string (string = texto)

seq = "Anderson Soares"
letra = seq[9]
print (letra)

#navegando pelo índice

seq = "Anderson Soares"

print (seq[0:8])

#imprimindo parte de uma string