# -*- coding: utf-8 -*-
"""tuplas-estruturadedados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fl55YHuAODggCN8lbzUoHiETNk3LASht
"""

type(T)

tupla = (1,2,3,4,5,6)
lista = [1,2,3,4,5,6]
dicionario = {1,2,3,4,5,6}

tuple(tupla)

print(dicionario)
print(lista)
print(tupla)