# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nLCcZbgm-VO_N-XVqhVOE4oStbly0Qn4
"""

var1 = 1 #variavel inteira
var2 = 1.1 #variavel flutuante
var3 = "string" #textual
var4 = True
var4 = False

print(var1)
print(var2)
print(var3)
print(var4)