# -*- coding: utf-8 -*-
"""vetores-array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rOsgHyWBSfAJen8QM9-vsKJz3bJsujpw
"""

import numpy as np

vetor = np.array([1,2,3,4,5,6])
tuple(vetor)