# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zd1_zwMnXkCZ85ei3rP4Xj8okO8OwQTW

Laço While:
"""

k = 0

while k <- 10:
  print(k)
  k = k + 1 # pode usar também (k += 1)

"""Pass, break, continue:"""

for letra in "Programador":
  if letra == 'a':
    pass
  print(letra)

# passa e nada acontece

for letra in "Programador":
  if letra == 'a':
    continue
  print(letra)

  #executa o comando

for letra in "Programador":
  if letra == 'a':
    break
  print(letra)

  #para o loop