# -*- coding: utf-8 -*-
"""while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNouzs9dwJOt9RinF3nAlHLSi-zql49i
"""

x = 1

while x < 10:
    print(x)
    x += 1 # x = x + 1 "notação especial da linguagem python"