# -*- coding: utf-8 -*-
"""zip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R_zI_sscLH-R3-Y0JV-bK5yg31WuuhWl
"""

#zip

lista1 = [1, 2, 3, 4, 5]
lista2 = ["Abacate", "bola", "cachorro", "dinheiro", "elefante"]

for numero, nome in zip(lista1, lista2):
  print(numero, nome)